pull_request_rules:
  - name: Automatic squash merge on approval
    conditions:
        - and:
          - "#approved-reviews-by>=1"
          - "check-success=build"
          - "-author=weblate"
    actions:
      merge:
        method: squash
        commit_message_template: |-
          {{ title }} (#{{number}})
          {{ body }} 

  - name: Automatic regular merge for Weblate PRs
    conditions:
        - and:
          - "#approved-reviews-by>=1"
          - "check-success=build"
          - "author=weblate"
    actions:
      merge:
        method: merge
        commit_message_template: |-
          {{ title }} (#{{number}})
          {{ body }} 
        
  - name: automatic update for PR marked as “Keep-updated“
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label="Keep-updated"
    actions:
      update:
