pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
          - "#approved-reviews-by>=1"
          - "check-success=build"
    actions:
      merge:
        method: squash

  - name: automatic update for PR marked as “Keep-updated“
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label="Keep-updated"
    actions:
      update:
