name: Deploy to hedy.org
on:
  # This gets run by hand
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Require one of these roles, configured ON THE REPOSITORY itself
      # (On the Organization is not enough)
      - if: github.actor.role != 'Maintainer' && github.actor.role != 'Admin'
        run: |
          echo "You must be a Maintainer or Admin to run this workflow." >&2
          exit 1
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hedy-beta
          heroku_email: felienne@gmail.com
