name: Check PEP8 compliance with flake8 and autoformat with black

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: black autoformat check
        uses: psf/black@stable
        with:
          options: "--check --diff"
          version: "~= 23.0"
