# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# If you change this name, don't forget to change deploy-to-alpha.yml
name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Install Nodejs dependencies
      run: |
        npm ci
    - name: Generate grammar files
      run: |
        python ./content/yaml_to_lark_utils.py
    - name: Compiling Babel translations
      run: |
        pybabel compile -f -d translations
    - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '^grammars/' }
          $HasDiff = $SourceDiff.Length -gt 0
          
          # Set the output named "docs_changed"
          Write-Host "::set-output name=docs_changed::$HasDiff"
    - shell: pwsh
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: build-tools/github/validate --all
    - shell: pwsh
        if: steps.check_file_changed.outputs.docs_changed != 'True'
        run: build-tools/github/validate
