# Script to regenerate the TypeScript on the main branch, if it ever happens
# that the JS bundle we find there is out of sync.
name: Automatically update JavaScript bundle

on:
  push:
    branches: [ main ]

jobs:
  update_javascript:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

        # This is necessary to bypass branch protection (which will disallow non-reviewed pushes otherwise)
        token: ${{ secrets.FELIENNE_GITHUB_ACCESS_TOKEN }}
    - name: Install Nodejs dependencies
      run: |
        npm ci

    - name: Compile TypeScript to JavaScript
      run: build-tools/heroku/generate-typescript

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: Automatically update JavaScript bundle 🤖 beep boop
        branch: main
        file_pattern: static/js/*.js* highlighting/*/*.json
      env:
        # This is necessary to bypass branch protection (which will disallow non-reviewed pushes otherwise)
        GITHUB_TOKEN: ${{ secrets.FELIENNE_GITHUB_ACCESS_TOKEN }}
