# Script to regenerate the TypeScript on the main branch, if it ever happens
# that the JS bundle we find there is out of sync.
name: Automatically update JavaScript bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_javascript:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

        # This is necessary to bypass branch protection (which will disallow non-reviewed pushes otherwise)
        token: ${{ secrets.FELIENNE_GITHUB_ACCESS_TOKEN }}
        
        # This is necessary to check out the 
    - name: Install Nodejs dependencies
      run: |
        npm ci

    - name: Compile TypeScript to JavaScript
      run: build-tools/heroku/generate-grammars-and-js

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      if: ${{ github.event_name == "push" }}
      with:
        commit_message: Automatically update JavaScript bundle 🤖 beep boop
        branch: ${{ github.head_ref }}
      env:
        # This is necessary to bypass branch protection (which will disallow non-reviewed pushes otherwise)
        GITHUB_TOKEN: ${{ secrets.FELIENNE_GITHUB_ACCESS_TOKEN }}
